[build]
  base = "marketplace"
  command = "ng build --configuration=production"
  publish = "dist/marketplace"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
